const quizQuestionArray = [
  {
    id: 1,
    question: "What is the capital of Denmark?",
    options: [
      { text: "Berlin", isCorrect: false },
      { text: "Copenhagen", isCorrect: true },
      { text: "Madrid", isCorrect: false },
      { text: "Rome", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: Copenhagen",
  },
  {
    id: 2,
    question: "What is 2 + 2?",
    options: [
      { text: "3", isCorrect: false },
      { text: "4", isCorrect: true },
      { text: "5", isCorrect: false },
      { text: "6", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: 4",
  },
  {
    id: 3,
    question: "Which planet is known as the Red Planet?",
    options: [
      { text: "Earth", isCorrect: false },
      { text: "Mars", isCorrect: true },
      { text: "Jupiter", isCorrect: false },
      { text: "Saturn", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: Mars",
  },
  {
    id: 4,
    question: "Who wrote 'Hamlet'?",
    options: [
      { text: "Shakespeare", isCorrect: true },
      { text: "Dickens", isCorrect: false },
      { text: "Austen", isCorrect: false },
      { text: "Hemingway", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: Shakespeare",
  },
  {
    id: 5,
    question: "What is the largest ocean on Earth?",
    options: [
      { text: "Atlantic", isCorrect: false },
      { text: "Indian", isCorrect: false },
      { text: "Arctic", isCorrect: false },
      { text: "Pacific", isCorrect: true },
    ],
    explanation: "The Correct Answer Is: Pacific",
  },
  {
    id: 6,
    question: "What is the square root of 64?",
    options: [
      { text: "6", isCorrect: false },
      { text: "7", isCorrect: false },
      { text: "8", isCorrect: true },
      { text: "9", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: 8",
  },
  {
    id: 7,
    question: "Which animal is known as the king of the jungle?",
    options: [
      { text: "Tiger", isCorrect: false },
      { text: "Elephant", isCorrect: false },
      { text: "Lion", isCorrect: true },
      { text: "Cheetah", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: Lion",
  },
  {
    id: 8,
    question: "What is the currency of Japan?",
    options: [
      { text: "Yuan", isCorrect: false },
      { text: "Yen", isCorrect: true },
      { text: "Won", isCorrect: false },
      { text: "Ringgit", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: Yen",
  },
  {
    id: 9,
    question: "Which country is the largest by land area?",
    options: [
      { text: "Canada", isCorrect: false },
      { text: "United States", isCorrect: false },
      { text: "China", isCorrect: false },
      { text: "Russia", isCorrect: true },
    ],
    explanation: "The Correct Answer Is: Russia",
  },
  {
    id: 10,
    question: "What is the tallest mountain in the world?",
    options: [
      { text: "K2", isCorrect: false },
      { text: "Mount Everest", isCorrect: true },
      { text: "Kangchenjunga", isCorrect: false },
      { text: "Lhotse", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: Mount Everest",
  },
  {
    id: 11,
    question: "Who painted the Mona Lisa?",
    options: [
      { text: "Van Gogh", isCorrect: false },
      { text: "Picasso", isCorrect: false },
      { text: "Da Vinci", isCorrect: true },
      { text: "Rembrandt", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: Da Vinci",
  },
  {
    id: 12,
    question: "Which element has the chemical symbol 'O'?",
    options: [
      { text: "Oxygen", isCorrect: true },
      { text: "Osmium", isCorrect: false },
      { text: "Ozone", isCorrect: false },
      { text: "Opium", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: Oxygen",
  },
  {
    id: 13,
    question: "What is the smallest country in the world?",
    options: [
      { text: "Monaco", isCorrect: false },
      { text: "San Marino", isCorrect: false },
      { text: "Vatican City", isCorrect: true },
      { text: "Liechtenstein", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: Vatican City",
  },
  {
    id: 14,
    question: "Who was the first president of the United States?",
    options: [
      { text: "George Washington", isCorrect: true },
      { text: "Thomas Jefferson", isCorrect: false },
      { text: "Abraham Lincoln", isCorrect: false },
      { text: "John Adams", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: George Washington",
  },
  {
    id: 15,
    question: "What is the speed of light?",
    options: [
      { text: "299,792 km/s", isCorrect: true },
      { text: "150,000 km/s", isCorrect: false },
      { text: "100,000 km/s", isCorrect: false },
      { text: "500,000 km/s", isCorrect: false },
    ],
    explanation: "The Correct Answer Is: 299,792 km/s",
  },
];
